responses: &responses
    "200":
      description: 成功
    "401":
      description: 没有权限
    "429":
      description: 请求次数过多
    "503":
      description: 服务器内部错误
swagger: "2.0"
info:
  version: "0.0.1"
  title: Sport
  license:
    name: "Front"
    url: "http://localhost:8080"
host: localhost:10010
basePath: /
tags:
  - name: "baseinfo"
    description: "sport info base"
    externalDocs:
      description: "sportBase"
      url: "http://localhost:8080"
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /sportsAllMethod:
    x-swagger-router-controller: baseinfo
    x-swagger-router-handle-subpaths": true
    get:
      tags:
        - "baseinfo"
      consumes:
        - application/json
      description: Returns all methods
      operationId: sportsAllBends
      responses: *responses
  /sportsAllStraight:
    x-swagger-router-controller: baseinfo
    get:
      tags:
        - "baseinfo"
      consumes:
        - "application/json"
      description: Returns all straight roads
      operationId: sportsAllStraight
      responses: *responses
  /sportsAllBend:
    x-swagger-router-controller: baseinfo
    get:
      tags:
        - "baseinfo"
      consumes:
        - "application/json"
      description: Returns all bend roads
      operationId: sportsAllBend
      responses: *responses
  /swagger:
    x-swagger-pipe: swagger_raw
