swagger: "2.0"
info:
  version: "0.0.1"
  title: Sport
  license:
    name: "Front"
    url: "http://localhost:8080"
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#tags
tags:
  - name: "sportBase"
    description: "sport info base"
    externalDocs:
      description: "sportBasesss"
      url: "http://localhost:8080"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /sportinfo:
    # binds a127 app logic to a route
    x-swagger-router-controller: sportinfo
    get:
      tags:
        - "sportBase"
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: sportBaseget
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - "sportBase"
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: sportBaseput
      parameters:
        - name: body
          in: body
          description: The name of the person to whom to say hello
          required: true
          schema:
            type: object
            required:
              - "sportname"
              - "sportBeginTime"
              - "sportEndTime"
              - "sportday"
              - "straroad"
              - "benroad"
              - "methodroad"
              - "comgroup"
            properties:
              sportname:
                type: string
                example: "yundonghui"
              sportBeginTime:
                type: string
                example: "2017-2-1"
              sportEndTime:
                type: string
                example: "2017-2-1"
              sportday:
                type: integer
                example: 2
              straroad:
                type: string
                example: "一道"
              benroad:
                type: string
                example: "一道"
              methodroad:
                type: string
                example: "手记时"
              comgroup:
                type: string
                example: "['A组', 'B组']"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sportsAllroad:
    # binds a127 app logic to a route
    x-swagger-router-controller: sportinfo
    # x-swagger-router-handle-subpaths": true
    get:
      tags:
        - "sportBase"
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: sportRoad
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
