responses: &responses
    "200":
      description: 成功
    "401":
      description: 没有权限
    "429":
      description: 请求次数过多
    "503":
      description: 服务器内部错误
swagger: "2.0"
info:
  version: "0.0.1"
  title: Sport
  license:
    name: "Front"
    url: "http://localhost:8080"
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#tags
tags:
  - name: "baseinfo"
    description: "sport info base"
    externalDocs:
      description: "sportBase"
      url: "http://localhost:8080"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /sportsAllBends:
    # binds a127 app logic to a route
    x-swagger-router-controller: baseinfo
    x-swagger-router-handle-subpaths": true
    get:
      tags:
        - "baseinfo"
      consumes:
        - application/json
      description: Returns all methods
      # used as the method name of the controller
      operationId: sportsAllBends
      responses: *responses
  # /sportsAllStraights:
  #   # binds a127 app logic to a route
  #   x-swagger-router-controller: baseinfo
  #   # x-swagger-router-handle-subpaths": true
  #   get:
  #     tags:
  #       - "baseinfo"
  #     consumes:
  #       - "application/json"
  #     description: Returns all straight roads
  #     # used as the method name of the controller
  #     operationId: sportsAllStraight
  #     responses: *responses
  #     headers:
  # /sportsAllBends:
  #   # binds a127 app logic to a route
  #   x-swagger-router-controller: baseinfo
  #   # x-swagger-router-handle-subpaths": true
  #   get:
  #     tags:
  #       - "baseinfo"
  #     consumes:
  #       - "application/json"
  #     description: Returns all bend roads
  #     # used as the method name of the controller
  #     operationId: sportsAllBend
  #     responses: *responses
  # /sportinfo:
  #   # binds a127 app logic to a route
  #   x-swagger-router-controller: sportinfo
  #   get:
  #     tags:
  #       - "baseinfo"
  #     description: Returns 'Hello' to the caller
  #     # used as the method name of the controller
  #     operationId: sportBaseget
  #     responses: *responses
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
